# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-17 01:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_mascota', '0001_initial'),
        ('app_usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_publicacion', models.DateTimeField(auto_created=True, auto_now=True)),
                ('descripcion', models.TextField()),
                ('titulo', models.CharField(blank=True, max_length=35, null=True)),
                ('tipo_aviso', models.SmallIntegerField(choices=[(1, 'Aviso Adopcion'), (2, 'Aviso Adoptar'), (3, 'Aviso Desaparecida'), (4, 'Aviso Encontrada')])),
            ],
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.ImageField(upload_to='media/image')),
            ],
        ),
        migrations.CreateModel(
            name='AvisoAdopcion',
            fields=[
                ('aviso_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_aviso.Aviso')),
                ('mascota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_mascota.Mascota')),
            ],
            bases=('app_aviso.aviso',),
        ),
        migrations.CreateModel(
            name='AvisoAdoptar',
            fields=[
                ('aviso_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_aviso.Aviso')),
                ('mascota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_mascota.Mascota')),
            ],
            bases=('app_aviso.aviso',),
        ),
        migrations.CreateModel(
            name='AvisoDesaparecida',
            fields=[
                ('aviso_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_aviso.Aviso')),
                ('fecha_desaparecida', models.DateField()),
                ('lugar', models.CharField(max_length=150)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_mascota.Mascota')),
            ],
            bases=('app_aviso.aviso',),
        ),
        migrations.CreateModel(
            name='AvisoEncontrada',
            fields=[
                ('aviso_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_aviso.Aviso')),
                ('fecha_encontrada', models.DateField()),
                ('lugar', models.CharField(max_length=150)),
            ],
            bases=('app_aviso.aviso',),
        ),
        migrations.AddField(
            model_name='imagen',
            name='aviso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='app_aviso.Aviso'),
        ),
        migrations.AddField(
            model_name='aviso',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_usuario.Usuario'),
        ),
    ]
