# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-31 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_aviso', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avisodesaparecida',
            old_name='fecha',
            new_name='fecha_desaparecida',
        ),
        migrations.AlterField(
            model_name='aviso',
            name='fecha_publicacion',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
    ]
