# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-31 22:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_aviso', '0002_auto_20180131_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aviso',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_usuario.Usuario'),
        ),
        migrations.AlterField(
            model_name='avisoadopcion',
            name='mascota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_mascota.Mascota'),
        ),
        migrations.AlterField(
            model_name='avisoadoptar',
            name='mascota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_mascota.Mascota'),
        ),
    ]
